# Generated by Django 6.0.4 on 2026-09-05 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        ('documents', '0002_document_error_message_document_file_extension_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionProvenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('section_heading', models.CharField(blank=True, max_length=512)),
                ('table_reference', models.CharField(blank=True, max_length=128)),
                ('sheet_name', models.CharField(blank=True, max_length=256)),
                ('row_index', models.PositiveIntegerField(blank=True, null=True)),
                ('col_index', models.PositiveIntegerField(blank=True, null=True)),
                ('extraction_method', models.CharField(blank=True, max_length=30)),
                ('ocr_used', models.BooleanField(default=False)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('source_reference', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provenance', to='datasets.structuredrecord')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extractor_type', models.CharField(choices=[('pdf_text', 'PDF Text'), ('pdf_ocr', 'PDF OCR'), ('docx', 'DOCX'), ('xlsx', 'XLSX'), ('csv', 'CSV'), ('txt', 'TXT'), ('image_ocr', 'Image OCR')], max_length=30)),
                ('ocr_used', models.BooleanField(default=False)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('extraction_metadata', models.JSONField(blank=True, default=dict)),
                ('raw_text', models.TextField(blank=True)),
                ('extracted_tables', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('ocr_unavailable', 'OCR Unavailable')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_result', to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='ValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(blank=True, max_length=256)),
                ('issue_type', models.CharField(choices=[('missing_required', 'Missing Required'), ('duplicate', 'Duplicate'), ('invalid_numeric', 'Invalid Numeric'), ('invalid_date', 'Invalid Date'), ('inconsistent_unit', 'Inconsistent Unit'), ('suspicious_value', 'Suspicious Value'), ('coordinate_error', 'Coordinate Error'), ('schema_mismatch', 'Schema Mismatch'), ('extraction_failure', 'Extraction Failure'), ('duplicate_record', 'Duplicate Record')], max_length=30)),
                ('severity', models.CharField(choices=[('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR')], max_length=10)),
                ('original_value', models.TextField(blank=True)),
                ('suggested_value', models.TextField(blank=True)),
                ('explanation', models.TextField()),
                ('confidence', models.FloatField(default=1.0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_results', to='documents.document')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datasets.structuredrecord')),
            ],
        ),
    ]
