"""
apps.maintainer — MaintainerSuggestion model

Phase 4: Represents a single suggestion to correct a value in a StructuredRecord.

IMMUTABILITY GUARANTEE:
  Creating or approving a suggestion NEVER modifies source data.
  Only explicit application (apply endpoint) modifies the StructuredRecord.data_json.
  Original uploaded files are NEVER touched.
"""

from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class SuggestionStatus(models.TextChoices):
    PENDING = 'pending', 'Pending'
    APPROVED = 'approved', 'Approved'
    REJECTED = 'rejected', 'Rejected'
    APPLIED = 'applied', 'Applied'
    FAILED = 'failed', 'Failed'


class SuggestionSource(models.TextChoices):
    DETERMINISTIC = 'deterministic', 'Deterministic'
    AI = 'ai', 'AI-Assisted'


class SuggestionIssueType(models.TextChoices):
    WHITESPACE = 'whitespace', 'Whitespace Cleanup'
    NUMERIC_FORMAT = 'numeric_format', 'Numeric Formatting'
    COMMA_NUMBER = 'comma_number', 'Comma-Separated Number'
    PERCENTAGE = 'percentage', 'Percentage Formatting'
    DATE_FORMAT = 'date_format', 'Date Normalization'
    FINANCIAL_YEAR = 'financial_year', 'Financial Year Normalization'
    UNIT_NORMALIZATION = 'unit_normalization', 'Unit Normalization'
    CAPITALIZATION = 'capitalization', 'Capitalization / Name Cleanup'
    INVALID_NUMERIC = 'invalid_numeric', 'Invalid Numeric'
    INVALID_DATE = 'invalid_date', 'Invalid Date'
    MISSING_VALUE = 'missing_value', 'Missing Value'
    DUPLICATE = 'duplicate', 'Duplicate'
    INCONSISTENT_UNIT = 'inconsistent_unit', 'Inconsistent Unit'
    SUSPICIOUS_VALUE = 'suspicious_value', 'Suspicious Value'
    SCHEMA_MISMATCH = 'schema_mismatch', 'Schema Mismatch'
    CONTEXTUAL = 'contextual', 'Contextual AI Suggestion'


class MaintainerSuggestion(models.Model):
    """
    A single correction suggestion for a field in a StructuredRecord.

    State machine:
      PENDING → APPROVED → APPLIED
      PENDING → REJECTED
      APPROVED → FAILED  (on application error)

    Creating a suggestion NEVER modifies any source data.
    APPROVE DOES NOT APPLY — application is explicit and separate.
    """

    # --- Dataset / Record reference ---
    dataset = models.ForeignKey(
        'datasets.StructuredDataset',
        on_delete=models.CASCADE,
        related_name='suggestions',
        help_text='Dataset this suggestion belongs to.',
    )
    record = models.ForeignKey(
        'datasets.StructuredRecord',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='suggestions',
        help_text='Specific record (row) this suggestion targets.',
    )
    document = models.ForeignKey(
        'documents.Document',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='maintainer_suggestions',
        help_text='Source document (denormalized for convenience).',
    )

    # --- Field and values ---
    field_name = models.CharField(
        max_length=256,
        blank=True,
        help_text='Column / field name within the record.',
    )
    original_value = models.TextField(
        blank=True,
        help_text='Original value from the source record (never changed).',
    )
    suggested_value = models.TextField(
        blank=True,
        help_text='Proposed corrected value.',
    )
    applied_value = models.TextField(
        blank=True,
        help_text='Value actually written on application (may differ if further sanitized).',
    )

    # --- Classification ---
    issue_type = models.CharField(
        max_length=30,
        choices=SuggestionIssueType.choices,
        default=SuggestionIssueType.WHITESPACE,
        db_index=True,
    )
    reason = models.TextField(
        help_text='Human-readable explanation of why this change is suggested.',
    )
    confidence = models.FloatField(
        default=1.0,
        help_text='Confidence score 0.0–1.0.',
    )
    suggestion_source = models.CharField(
        max_length=20,
        choices=SuggestionSource.choices,
        default=SuggestionSource.DETERMINISTIC,
        db_index=True,
        help_text='Whether this was generated by deterministic rules or AI fallback.',
    )

    # --- Provenance ---
    provenance = models.ForeignKey(
        'pipeline.ExtractionProvenance',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='maintainer_suggestions',
        help_text='Source extraction provenance record if available.',
    )

    # --- Lifecycle ---
    status = models.CharField(
        max_length=20,
        choices=SuggestionStatus.choices,
        default=SuggestionStatus.PENDING,
        db_index=True,
    )
    error_message = models.TextField(
        blank=True,
        help_text='Error detail if application failed.',
    )

    # --- Audit fields ---
    created_by = models.ForeignKey(
        User,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='created_suggestions',
        help_text='User who triggered suggestion generation.',
    )
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    reviewed_by = models.ForeignKey(
        User,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='reviewed_suggestions',
        help_text='User who approved or rejected this suggestion.',
    )
    reviewed_at = models.DateTimeField(null=True, blank=True)
    applied_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Maintainer Suggestion'
        verbose_name_plural = 'Maintainer Suggestions'
        indexes = [
            models.Index(fields=['dataset', 'status']),
            models.Index(fields=['dataset', 'issue_type']),
            models.Index(fields=['record', 'field_name']),
        ]

    def __str__(self):
        return (
            f'Suggestion [{self.status}] {self.field_name}: '
            f'"{self.original_value}" → "{self.suggested_value}"'
        )
