# Generated by Django 6.1.1 on 2026-09-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GSIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession_no', models.CharField(blank=True, db_index=True, help_text='GSI accession number.', max_length=128)),
                ('fsp_id', models.CharField(blank=True, help_text='Field Season Program ID.', max_length=128)),
                ('title', models.TextField(help_text='Report title.')),
                ('author', models.CharField(blank=True, help_text='Author(s) of the report.', max_length=512)),
                ('state', models.CharField(blank=True, db_index=True, help_text='State(s) covered by this report.', max_length=256)),
                ('toposheet_no', models.CharField(blank=True, help_text='Survey of India Toposheet number(s).', max_length=256)),
                ('year_from', models.CharField(blank=True, help_text='Start year of field season.', max_length=8)),
                ('year_to', models.CharField(blank=True, help_text='End year of field season.', max_length=8)),
                ('region', models.CharField(blank=True, db_index=True, help_text='GSI Regional Office code (ER, WR, SR, NR, CR, NER, etc.).', max_length=16)),
                ('mission', models.CharField(blank=True, help_text='GSI Mission code.', max_length=128)),
                ('theme', models.CharField(blank=True, db_index=True, help_text='Thematic area (e.g. Coal and Lignite Exploration).', max_length=256)),
            ],
            options={
                'verbose_name': 'GSI Report',
                'verbose_name_plural': 'GSI Reports',
                'ordering': ['-year_from', 'accession_no'],
                'indexes': [models.Index(fields=['state', 'theme'], name='phase8_gsir_state_72da36_idx'), models.Index(fields=['region'], name='phase8_gsir_region_915293_idx')],
            },
        ),
        migrations.CreateModel(
            name='MineLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mine_name', models.CharField(db_index=True, help_text='Official mine name as recorded in mining_map_phase8.csv', max_length=256)),
                ('latitude', models.FloatField(help_text='Decimal latitude (WGS-84). Verified within Indian bounds (6–38°N).')),
                ('longitude', models.FloatField(help_text='Decimal longitude (WGS-84). Verified within Indian bounds (68–98°E).')),
                ('state', models.CharField(db_index=True, help_text='State as recorded in dataset.', max_length=128)),
                ('district', models.CharField(blank=True, db_index=True, help_text='District as recorded in dataset.', max_length=128)),
                ('coalfield', models.CharField(blank=True, db_index=True, help_text='Coalfield name as recorded in dataset.', max_length=256)),
                ('subsidiary', models.CharField(blank=True, db_index=True, help_text='CIL subsidiary (e.g. CCL, BCCL, SECL).', max_length=128)),
                ('mine_type', models.CharField(blank=True, db_index=True, help_text='Mine type as recorded (OC=Open-cast, UG=Underground, Mixed).', max_length=64)),
                ('production_mt', models.FloatField(blank=True, help_text='Production in Million Tonnes for reporting year.', null=True)),
                ('year', models.CharField(blank=True, help_text='Financial year of the data (e.g. 2024-25).', max_length=16)),
            ],
            options={
                'verbose_name': 'Mine Location',
                'verbose_name_plural': 'Mine Locations',
                'ordering': ['mine_name'],
                'indexes': [models.Index(fields=['subsidiary', 'state'], name='phase8_mine_subsidi_dd7610_idx'), models.Index(fields=['coalfield'], name='phase8_mine_coalfie_57dac1_idx')],
            },
        ),
        migrations.CreateModel(
            name='OcbisBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsidiary_or_state', models.CharField(blank=True, db_index=True, help_text='CIL subsidiary or State associated with the block.', max_length=128)),
                ('coalfield', models.CharField(blank=True, db_index=True, help_text='Coalfield name.', max_length=256)),
                ('block_name', models.CharField(db_index=True, help_text='Name of the coal block.', max_length=256)),
                ('act_type', models.CharField(blank=True, help_text='Applicable legislation (e.g. MMDR, CIL).', max_length=64)),
                ('allocated_to', models.CharField(blank=True, help_text='Entity to whom block is allocated, or Unallocated.', max_length=256)),
            ],
            options={
                'verbose_name': 'OCBIS Coal Block',
                'verbose_name_plural': 'OCBIS Coal Blocks',
                'ordering': ['coalfield', 'block_name'],
                'indexes': [models.Index(fields=['coalfield', 'subsidiary_or_state'], name='phase8_ocbi_coalfie_986eec_idx')],
            },
        ),
    ]
