# Generated by Django 6.0.4 on 2026-09-06 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_document_error_message_document_file_extension_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='User query text.')),
                ('query_type', models.CharField(choices=[('STRUCTURED', 'Structured Data'), ('DOCUMENT', 'Document Search'), ('HYBRID', 'Hybrid (Structured + Document)')], default='DOCUMENT', help_text='Routing classification of the query.', max_length=32)),
                ('answer', models.TextField(help_text='Grounded answer generated for the query.')),
                ('confidence', models.CharField(choices=[('HIGH', 'High Confidence'), ('MEDIUM', 'Medium Confidence'), ('LOW', 'Low Confidence')], default='LOW', help_text='Assessed confidence based on evidence quality.', max_length=16)),
                ('sources', models.JSONField(blank=True, default=list, help_text='List of citations with full provenance metadata.')),
                ('evidence_count', models.PositiveIntegerField(default=0, help_text='Count of evidence units supporting the answer.')),
                ('source_count', models.PositiveIntegerField(default=0, help_text='Count of distinct source documents or datasets cited.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the query was executed.')),
                ('user', models.ForeignKey(help_text='User who submitted the query.', on_delete=django.db.models.deletion.CASCADE, related_name='ai_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Query Log',
                'verbose_name_plural': 'AI Query Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField(help_text='0-indexed sequential position of this chunk within the document.')),
                ('content', models.TextField(help_text='Textual content of the chunk.')),
                ('content_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the content for deduplication and idempotency.', max_length=64)),
                ('page_number', models.PositiveIntegerField(blank=True, help_text='1-based page number where this chunk originated, if applicable.', null=True)),
                ('section_heading', models.CharField(blank=True, help_text='Heading or section title under which this chunk appears.', max_length=512)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (e.g. table_reference, extractor_type, ocr_used).')),
                ('token_count', models.PositiveIntegerField(default=0, help_text='Approximate token count for the chunk.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(help_text='Source document for this chunk.', on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document')),
            ],
            options={
                'verbose_name': 'Document Chunk',
                'verbose_name_plural': 'Document Chunks',
                'ordering': ['document', 'chunk_index'],
                'unique_together': {('document', 'chunk_index')},
            },
        ),
    ]
