# Generated by Django 6.0.4 on 2026-09-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('document.uploaded', 'Document Uploaded'), ('document.processed', 'Document Processed'), ('document.failed', 'Document Processing Failed'), ('document.reviewed', 'Document Reviewed'), ('document.approved', 'Document Approved'), ('document.rejected', 'Document Rejected'), ('document.deleted', 'Document Deleted'), ('dataset.created', 'Dataset Created'), ('dataset.updated', 'Dataset Updated'), ('ai.query', 'AI Query Submitted'), ('ai.report', 'AI Report Generated'), ('user.login', 'User Login'), ('user.logout', 'User Logout'), ('user.password_change', 'Password Changed'), ('system.health_check', 'Health Check'), ('system.backup', 'System Backup')], db_index=True, help_text='Type of event that occurred.', max_length=64)),
                ('actor', models.CharField(blank=True, db_index=True, help_text='Username or email of the user who performed the action.', max_length=256)),
                ('actor_ip', models.GenericIPAddressField(blank=True, help_text='IP address of the actor at time of action.', null=True)),
                ('resource_type', models.CharField(blank=True, help_text='Type of resource affected (e.g. "document", "dataset").', max_length=64)),
                ('resource_id', models.CharField(blank=True, db_index=True, help_text='ID or identifier of the affected resource.', max_length=256)),
                ('description', models.TextField(help_text='Human-readable description of what happened.')),
                ('metadata_json', models.JSONField(blank=True, default=dict, help_text='Additional structured context for this event.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the event occurred (server time, UTC).')),
            ],
            options={
                'verbose_name': 'Audit Event',
                'verbose_name_plural': 'Audit Events',
                'ordering': ['-timestamp'],
            },
        ),
    ]
