# Generated by Django 6.0.4 on 2026-09-05 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        ('documents', '0002_document_error_message_document_file_extension_and_more'),
        ('pipeline', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintainerSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(blank=True, help_text='Column / field name within the record.', max_length=256)),
                ('original_value', models.TextField(blank=True, help_text='Original value from the source record (never changed).')),
                ('suggested_value', models.TextField(blank=True, help_text='Proposed corrected value.')),
                ('applied_value', models.TextField(blank=True, help_text='Value actually written on application (may differ if further sanitized).')),
                ('issue_type', models.CharField(choices=[('whitespace', 'Whitespace Cleanup'), ('numeric_format', 'Numeric Formatting'), ('comma_number', 'Comma-Separated Number'), ('percentage', 'Percentage Formatting'), ('date_format', 'Date Normalization'), ('financial_year', 'Financial Year Normalization'), ('unit_normalization', 'Unit Normalization'), ('capitalization', 'Capitalization / Name Cleanup'), ('invalid_numeric', 'Invalid Numeric'), ('invalid_date', 'Invalid Date'), ('missing_value', 'Missing Value'), ('duplicate', 'Duplicate'), ('inconsistent_unit', 'Inconsistent Unit'), ('suspicious_value', 'Suspicious Value'), ('schema_mismatch', 'Schema Mismatch'), ('contextual', 'Contextual AI Suggestion')], db_index=True, default='whitespace', max_length=30)),
                ('reason', models.TextField(help_text='Human-readable explanation of why this change is suggested.')),
                ('confidence', models.FloatField(default=1.0, help_text='Confidence score 0.0–1.0.')),
                ('suggestion_source', models.CharField(choices=[('deterministic', 'Deterministic'), ('ai', 'AI-Assisted')], db_index=True, default='deterministic', help_text='Whether this was generated by deterministic rules or AI fallback.', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applied', 'Applied'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error detail if application failed.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who triggered suggestion generation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_suggestions', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(help_text='Dataset this suggestion belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='datasets.structureddataset')),
                ('document', models.ForeignKey(blank=True, help_text='Source document (denormalized for convenience).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintainer_suggestions', to='documents.document')),
                ('provenance', models.ForeignKey(blank=True, help_text='Source extraction provenance record if available.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintainer_suggestions', to='pipeline.extractionprovenance')),
                ('record', models.ForeignKey(blank=True, help_text='Specific record (row) this suggestion targets.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='datasets.structuredrecord')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='User who approved or rejected this suggestion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maintainer Suggestion',
                'verbose_name_plural': 'Maintainer Suggestions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['dataset', 'status'], name='maintainer__dataset_514b38_idx'), models.Index(fields=['dataset', 'issue_type'], name='maintainer__dataset_e5d22f_idx'), models.Index(fields=['record', 'field_name'], name='maintainer__record__b6a27a_idx')],
            },
        ),
    ]
