# Generated by Django 6.0.4 on 2026-09-04 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Human-readable document title.', max_length=512)),
                ('file', models.FileField(blank=True, help_text='Uploaded file path (relative to MEDIA_ROOT).', null=True, upload_to='documents/%Y/%m/%d/')),
                ('original_filename', models.CharField(blank=True, help_text='Original filename as uploaded by the user.', max_length=512)),
                ('file_size', models.PositiveBigIntegerField(blank=True, help_text='File size in bytes.', null=True)),
                ('mime_type', models.CharField(blank=True, help_text='MIME type detected at upload (e.g. application/pdf).', max_length=128)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('extracting', 'Extracting'), ('validating', 'Validating'), ('indexed', 'Indexed'), ('needs_review', 'Needs Review'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Reviewer notes or processing remarks.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded this document.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('ocr', 'OCR'), ('text_extraction', 'Text Extraction'), ('data_extraction', 'Data Extraction'), ('validation', 'Validation'), ('indexing', 'Indexing'), ('embedding', 'Embedding')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error traceback or message if job failed.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Job-specific metadata (page count, confidence scores, etc.).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='documents.document')),
            ],
            options={
                'verbose_name': 'Processing Job',
                'verbose_name_plural': 'Processing Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
