# Generated by Django 6.0.4 on 2026-09-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error details if upload, validation, or processing fails.'),
        ),
        migrations.AddField(
            model_name='document',
            name='file_extension',
            field=models.CharField(blank=True, db_index=True, help_text='Lowercased file extension with leading dot (e.g. .pdf).', max_length=32),
        ),
        migrations.AddField(
            model_name='document',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='True if the document has been archived/soft-deleted.'),
        ),
        migrations.AddField(
            model_name='document',
            name='sha256_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 cryptographic hash of the original file content.', max_length=64),
        ),
        migrations.AddField(
            model_name='document',
            name='storage_key',
            field=models.CharField(blank=True, db_index=True, help_text='Key used in storage backend.', max_length=512),
        ),
        migrations.AddField(
            model_name='document',
            name='stored_filename',
            field=models.CharField(blank=True, help_text='Safe storage filename/path.', max_length=512),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('queued', 'Queued'), ('processing', 'Processing'), ('extracting', 'Extracting'), ('validating', 'Validating'), ('indexed', 'Indexed'), ('needs_review', 'Needs Review'), ('processed', 'Processed'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=20),
        ),
    ]
