# Generated by Django 6.0.4 on 2026-09-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_error_message_document_file_extension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_reference',
            field=models.BooleanField(db_index=True, default=False, help_text='True if the document is official baseline reference data protected from removal.'),
        ),
    ]
