# Generated by Django 6.1.1 on 2026-09-07 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        ('documents', '0002_document_error_message_document_file_extension_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('report_type', models.CharField(choices=[('Production Report', 'Production Report'), ('Geological & Exploration Report', 'Geological & Exploration Report'), ('Mining Performance Report', 'Mining Performance Report'), ('Exploration Report', 'Exploration Report'), ('Coal Seam Analysis', 'Coal Seam Analysis'), ('Parliamentary Question Response', 'Parliamentary Question Response'), ('Administrative Query', 'Administrative Query'), ('Custom Report', 'Custom Report')], db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATING', 'Generating'), ('GENERATED', 'Generated'), ('UNDER_REVIEW', 'Under Review'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('EXPORTED', 'Exported'), ('FAILED', 'Failed')], db_index=True, default='DRAFT', max_length=32)),
                ('organization', models.CharField(blank=True, default='CMPDI (HQ)', max_length=128)),
                ('date_range', models.CharField(blank=True, default='All Available', max_length=128)),
                ('filters_json', models.JSONField(blank=True, default=dict, help_text='Filter criteria applied during report generation (e.g. subsidiary, FY).')),
                ('content_json', models.JSONField(blank=True, default=dict, help_text='Full structured content of the report (summary, KPIs, tables, trends, analysis, etc.).')),
                ('provenance_json', models.JSONField(blank=True, default=list, help_text='Source-backed traceability citations for all critical numbers and statements.')),
                ('export_format', models.CharField(blank=True, default='', max_length=16)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True, default='')),
                ('revision_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reports', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('source_datasets', models.ManyToManyField(blank=True, help_text='Underlying structured datasets providing verified facts and figures.', related_name='reports', to='datasets.structureddataset')),
                ('source_documents', models.ManyToManyField(blank=True, help_text='Source documents providing narrative and context evidence.', related_name='reports', to='documents.document')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
